<a href="https://colab.research.google.com/github/jitu619/SHALA2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [22]:
import numpy as np
a=np.random.random_sample((3,5))
b=np.random.random_sample((3,5))
print("a {}".format(a))
print("b {}".format(b))

a [[0.9455642  0.17468389 0.88460618 0.27455804 0.81149362]
 [0.47964627 0.83580689 0.26260128 0.69346516 0.79292421]
 [0.47023816 0.46531228 0.81254821 0.845319   0.14575079]]
b [[0.61994047 0.91123493 0.11842165 0.53939153 0.96345694]
 [0.99308575 0.41297616 0.2168791  0.8667018  0.6322413 ]
 [0.06991747 0.51132352 0.12424313 0.81131025 0.07727474]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [16]:
#As 0 is neither negetive nor postive so ideally i should omit it
#but later in the assigment we have to reshape it to 10*10
#therefore including 0
c=np.arange(0,100)
print(c)
print(c.shape)

d=np.zeros((3,3),dtype=float)
print(d)
print(d.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [10]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e=np.array(e)
print(e)
type(e)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [15]:
f=np.ones((5,5),dtype=int)
print(f)

g=np.eye(5)
print(g)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [24]:
h=c.reshape((10,10))
print(h.shape)

c_new=h.flatten()
print(c_new.shape)

if h.shape==c_new.shape:
  print("YES")
else:
  print("NO")

(10, 10)
(100,)
NO


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [32]:
A = np.random.rand(2,10,5)
A_new=A.transpose((2,0,1))
print(A_new.shape)
print(A_new)



(5, 2, 10)
[[[0.78529916 0.97482453 0.37818845 0.94842557 0.23751634 0.34722929
   0.40736275 0.00305909 0.35541432 0.6586474 ]
  [0.76366433 0.50300473 0.60600371 0.77382571 0.0659379  0.23878847
   0.95272012 0.11965984 0.29356078 0.18796495]]

 [[0.20452271 0.78085723 0.99861721 0.17780671 0.35838213 0.53189972
   0.61282906 0.61022998 0.65210591 0.35541792]
  [0.46176631 0.066098   0.60447778 0.42077713 0.66878748 0.45988059
   0.80743686 0.5233146  0.09600893 0.1630193 ]]

 [[0.41990275 0.2265907  0.88599886 0.48306325 0.82700793 0.08659911
   0.40593638 0.30289462 0.95269266 0.96861693]
  [0.70754612 0.48973199 0.00892946 0.70918934 0.42734387 0.91296509
   0.18069105 0.77402493 0.17268587 0.3763815 ]]

 [[0.17546753 0.17194399 0.91868201 0.31705337 0.25219799 0.05487532
   0.01287025 0.7794712  0.1988148  0.11135789]
  [0.68064599 0.624252   0.44309585 0.84868627 0.42605171 0.51806899
   0.23906786 0.53814128 0.76774245 0.00495059]]

 [[0.45102247 0.9499035  0.26985636 0.9912570

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [37]:
np.random.seed(0)
X = np.random.rand(10,5)
# print(X)
# Minimum value and index where it occured, for each column
print(X.min(axis=0),X.argmin(axis=0))
# Maximum value and the index where it occured, for each column
print(X.max(axis=0),X.argmax(axis=0))
# Minimum value and index where it occured, for each row
print(X.min(axis=1),X.argmin(axis=1))
# Maximum value and index where it occured, for each row
print(X.min(axis=1),X.argmin(axis=1))
# Minimum value and index where it occured, for the entire matrix
print(X.min(),X.argmin())
# Maximum value and index where it occured, for the entire matrix
print(X.max(),X.argmax())


[0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ] [3 3 9 8 6]
[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215] [4 4 5 1 3]
[0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ] [4 4 4 1 4 1 4 1 3 2]
[0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ] [4 4 4 1 4 1 4 1 3 2]
0.018789800436355142 34
0.978618342232764 20


Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [44]:
# Mean of each row
print(X.mean(axis=1))
# Mean of each column
print(X.mean(axis=0))
# Standard deviation of each row
print(X.std(axis=1))
# Standard deviation of each column
print(X.std(axis=0))
# Mean of the entire matrix
print(X.mean())
# Standard deviation of entire matrix
print(X.std())

[0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
[0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
[0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332]
[0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
0.5379651182755409
0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [60]:
np.random.seed(3)
Y = np.random.rand(10,10)
# Determinant
print(np.linalg.det(Y))
# Rank of the matrix
print(np.linalg.matrix_rank(Y))
# Diagonal Elements
print(np.diag(Y))
# Trace
print(np.trace(Y))
# Eigen values
eigen_val,eigen_vec=np.linalg.eig(Y)
print(eigen_val)
# Matrices obtained after Singular Value Decomposition
u,S,VT=np.linalg.svd(Y)
# Inverse if exists, otherwise Pseudo-Inverse
inverse=np.linalg.inv(Y)
psuedo_inverse=np.linalg.pinv(Y)
# Multiplication Y with X
print(np.matmul(Y,X))
# Element-wise multiplication of  Y  and its inverse(or pseudo-inverse)
print(np.dot(Y,inverse))

-0.012807808169095483
10
[0.5507979  0.45683322 0.44045372 0.84575087 0.4576864  0.36217621
 0.06152893 0.19897603 0.92672568 0.19638058]
4.497309545724899
[ 4.797525  +0.j          0.72411408+0.52238181j  0.72411408-0.52238181j
 -0.48250062+0.55413671j -0.48250062-0.55413671j -0.6909002 +0.j
 -0.25905659+0.32357377j -0.25905659-0.32357377j  0.2127855 +0.08352477j
  0.2127855 -0.08352477j]
[[2.95726101 2.04939653 3.09073485 3.22311637 1.78554985]
 [2.61266989 1.75663954 2.48635951 2.79783984 1.50654432]
 [2.98361778 2.02894044 2.82637865 2.88685728 1.69799548]
 [2.98565892 2.85485651 3.58995669 4.0073463  2.2697569 ]
 [2.49815821 1.97791033 2.77809758 2.71690515 1.59098767]
 [2.72146909 2.39905911 2.58780909 2.78212857 1.71792628]
 [2.22935358 1.74438251 2.94718357 2.48955906 2.05838199]
 [2.30476788 1.92350098 2.41698824 2.81379687 1.38016019]
 [2.91925254 2.36604123 3.53647969 3.30424184 2.52990887]
 [3.39559098 2.84629279 4.05845051 4.01068273 2.35816262]]


array([[ 1.00000000e+00, -3.90793144e-17,  3.65935406e-16,
         3.11342944e-16, -8.91983549e-16, -4.81506510e-17,
        -1.42655871e-16, -6.91246638e-16, -6.67910040e-17,
         1.33795870e-16],
       [ 1.42780307e-17,  1.00000000e+00, -6.98095657e-17,
        -1.52151045e-16, -4.63427918e-16, -1.05178821e-16,
         4.44443766e-17, -9.87040861e-17,  1.06466168e-16,
        -1.58597206e-16],
       [-1.44191947e-17, -4.68953161e-17,  1.00000000e+00,
         4.77076242e-17, -6.49165003e-16, -6.78141792e-17,
        -9.36855690e-18, -9.73600834e-16, -3.16087494e-17,
        -1.18238356e-16],
       [-1.41735142e-16,  2.10254036e-16,  1.43559668e-17,
         1.00000000e+00,  5.52648957e-17, -8.23073740e-18,
        -1.72594927e-18,  7.33409702e-17,  4.69571374e-17,
        -2.73245897e-16],
       [-1.71385362e-17, -3.79289464e-18, -2.27088068e-16,
         1.03307474e-16,  1.00000000e+00, -2.64623779e-17,
         1.14447652e-16,  2.15787383e-17, -1.42660749e-17,
        -2.

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [84]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"
df=pd.read_csv(file_url)
df.head()

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---



In [90]:
sex_dummy=pd.get_dummies(df['sex'])
embarked_dummy=pd.get_dummies(df['embarked'])
pclass_dummy=pd.get_dummies(df['pclass'])
titanic_data_new=pd.concat([sex_dummy,embarked_dummy,pclass_dummy],axis=1)
print(titanic_data_new)

      female  male  C  Q  S  1  2  3
0          1     0  0  0  1  1  0  0
1          0     1  0  0  1  1  0  0
2          1     0  0  0  1  1  0  0
3          0     1  0  0  1  1  0  0
4          1     0  0  0  1  1  0  0
...      ...   ... .. .. .. .. .. ..
1304       1     0  1  0  0  0  0  1
1305       1     0  1  0  0  0  0  1
1306       0     1  1  0  0  0  0  1
1307       0     1  1  0  0  0  0  1
1308       0     1  0  0  1  0  0  1

[1309 rows x 8 columns]




---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



In [91]:
df['age_new'] = df['age'].fillna((df['age'].mean()))
df['fare_new'] = df['fare'].fillna((df['fare'].mean()))
titanic_data_new=pd.concat([titanic_data_new,df['age_new'],df['fare_new']],axis=1)
print(titanic_data_new)

      female  male  C  Q  S  1  2  3    age_new  fare_new
0          1     0  0  0  1  1  0  0  29.000000  211.3375
1          0     1  0  0  1  1  0  0   0.920000  151.5500
2          1     0  0  0  1  1  0  0   2.000000  151.5500
3          0     1  0  0  1  1  0  0  30.000000  151.5500
4          1     0  0  0  1  1  0  0  25.000000  151.5500
...      ...   ... .. .. .. .. .. ..        ...       ...
1304       1     0  1  0  0  0  0  1  14.500000   14.4542
1305       1     0  1  0  0  0  0  1  29.881138   14.4542
1306       0     1  1  0  0  0  0  1  26.500000    7.2250
1307       0     1  1  0  0  0  0  1  27.000000    7.2250
1308       0     1  0  0  1  0  0  1  29.000000    7.8750

[1309 rows x 10 columns]


###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

In [0]:
import matplotlib.pyplot as plt

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.